### ISSUE TITLE
P-value significance threshold

### ISSUE THREAD

**Issue by LuziaThea** [caitiecollins/treeWAS#22] opened 2018-05-01 08:25 UTC
Hello Catie, 

Thank you so much for this great tool!
I have a question regarding the setting of the significance threshold. 
I observed that running your example data with either p.value = 1 or p.value = 0.01 the number of the combined significant loci doesn’t change, I get only small changes in the significant hits for the simultaneous and subsequent score. For the p.value = 1 setting I would have expected a way larger number of significant hits. Can you explain me why that isn’t the case?

If I understand correctly, you calculate the p-values in a count-based manner for both simulated and experimental scores. All the experimental scores that exceed the simulated score corresponding to the BH corrected threshold p-value are considered as significant. 

Thank you so much for your help.
Best, 
Luzia

**Comment by acgerstein** [comment] 2018-05-07 16:41
I have this concern so am posting here to be aware of any explanation. This tool looks like it should be fantastic!

**Comment by Yannovsky** [comment] 2018-05-13 16:52
I asked myself the same question. :)

**Comment by xavierdidelot** [comment] 2018-06-13 09:48
Sorry I was unable to reply earlier. I can see what you mean and was able to reproduce exactly the behaviour you described. The reason why we still get the same significance results when the base p-value is 1 instead of 0.01 is because the Bonferroni correction is very stringent. To check this, you can deactivate the Bonferroni correction using p.value.correct='false'. This is usually a bad idea, and in fact did not work until today but I just committed a fix to make it work. Actually it can be a good idea if you want to set your own p-value threshold without relying on the Bonferroni correction - but then of course you don't want to set this to p.value=1 (-:

**Closed by xavierdidelot** 2018-06-13 09:48 UTC
